### ISSUE TITLE
No way to abort game after crash

### ISSUE THREAD

**Issue by bleakley** [flend/web-brogue#1]
If a brogue game crashes, there is no way to abort the game. Clicking on "Start or continue game" automatically dumps you back to the lobby.

**Comment by flend** [comment]
Hi Brian,

Thanks for the report. There are some weird edge cases here with certain
types of crashes . Can you give me the username in question? Unfortunately
I'm out of the country right now but can look on my return.

Tom

**Comment by bleakley** [comment]
Hi Tom, the username is bleezy. Thanks.

**Comment by flend** [comment]
Hi Brian,

I've saved the logs and rebooted the server, which should hopefully fix the
problem. When I am back at home I will try to make a crashing brogue exe to
fully reproduce the problem.

Tom

**Comment by flend** [comment]
I believe this is fixed in the current version of the code. I tested with an executable which crashes when 'A' is pressed. I was able to start a new game.
