### ISSUE TITLE
Can't log in and Can't find a reset password link anywhere

### ISSUE THREAD

**Issue by sswainright** [flend/web-brogue#4]
How do you reset your password if you forgot? or did the all the credentials get purged recently.  I had a game going from a couple days ago I would like to finish

**Comment by flend** [comment]
Hi there. There's no password reset yet, unfortunately. However, there was no credential purge, so I'd suggest keep trying. Password reset will come eventually!

**Comment by sswainright** [comment]
Ok, thanks
